OnlineShoppingStore.webUI/Controllers/CartController.cs
using OnlineShoppingStore.Domain.Abstrat;
using OnlineShoppingStore.Domain.Entity;
using OnlineShoppingStore.webUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.webUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepusetory repusetory;
        private IOrderProcessor processor;
        public CartController(IProductRepusetory repu,IOrderProcessor proc)
        {
            processor = proc;
            repusetory = repu;
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View (new CartIndexModelView { Cart = cart, ReturnUrl = returnUrl });
        }

        public ViewResult Checkout()
        { 
        return View(new ShoppingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart,ShoppingDetails shoppingdetails)
        {
            if (cart.lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry Your Cart is Empty");
            }
            if (ModelState.IsValid)
            {
                processor.ProcessorOrder(cart, shoppingdetails);
                cart.Clear();
                return View("Complete");
            }
            else {
                return View(shoppingdetails);
            }
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView (cart);
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productid,string returnUrl) 
        {
            Product product = repusetory.Products.Where(p => p.ProductID == productid).FirstOrDefault();
            if (product != null) 
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productid, string returnUrl)
        {
            Product product = repusetory.Products.Where(p => p.ProductID == productid).FirstOrDefault();
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        
     
	}
}

OnlineShoppingStore.webUI/Controllers/NavigationController.cs
using OnlineShoppingStore.Domain.Abstrat;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.webUI.Controllers
{
    public class NavigationController : Controller
    {
        private IProductRepusetory repusetory;
         public NavigationController(IProductRepusetory repu)
         {
                repusetory=repu;
         }
         public PartialViewResult Manu(string category =null) 
         {
             ViewBag.SelectCategory = category;
             IEnumerable<string> catagoris = repusetory.Products
                                            .Select(s => s.Catagory)
                                            .Distinct()
                                            .OrderBy(x => x);
                        return PartialView(catagoris);
         }
        
	}
}

OnlineShoppingStore.webUI/Controllers/ProductController.cs
using OnlineShoppingStore.Domain.Abstrat;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.webUI.Models;

namespace OnlineShoppingStore.webUI.Controllers
{
    public class ProductController : Controller
    {
        protected readonly IProductRepusetory repusetory;
        public int Pagesize = 3;
        public ProductController(IProductRepusetory Repu)
        {
            repusetory = Repu;
        }
        public ViewResult List(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = repusetory.Products
                      .Where(p => category == null || p.Catagory == category)
                     .OrderBy(p => p.ProductID)
                     .Skip((page - 1) * Pagesize)
                     .Take(Pagesize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemPerPage = Pagesize,
                    TotalItems = category ==null ? repusetory.Products.Count()
                    : repusetory.Products.Where(p =>p.Catagory ==category).Count()
                },
                CurrentCategory = category
                
            };
            return View(model);
        }
	}
}

OnlineShoppingStore.webUI/Views/Shared/ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entity.Product

<div class="well">
    <h3>
        <strong>@Model.ProductName</strong>
        <span class="pull-right label label-primary">‎@Model.Price.ToString("c", System.Globalization.CultureInfo.CreateSpecificCulture("bn-BD"))</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(p => p.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add To Cart" />
        </div>
    }
    <span class="lead  "> @Model.Descriptions</span>
</div>

OnlineShoppingStore.webUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OnlineShoppingStore</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
       

        <a class="navbar-brand" href="#">
            <span class="hidden-xs"> Online Shopping Store</span>
            <div class="visible-xs">Online</div>
            <div class="visible-xs">Shopping</div>
            <div class="visible-xs">Store</div>
        </a>
       
        @Html.Action("Summary","Cart")
      
    </div>
    <div class="row panel">
        <div id="categoris" class="col-md-3">
            @Html.Action("Manu","Navigation")
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
    <div class="text-center panel-footer">
      <p>OnlineShoppingStore &copy copyright-2015 || @Html.ActionLink("Admin","Index","Admin")</p>
    </div>
</body>
</html>

OnlineShoppingStore.webUI/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body style="margin-left:auto;margin-right:auto">
    <div>
        
        @if (TempData["msg"] != null)
        { 
        <div class="alert alert-success">@TempData["msg"]</div>
        }
       
            @{
                var username = HttpContext.Current.User.Identity.Name;
                if (username != "")
                {
                    <h3>
                        @Html.ActionLink("Online Shopping Store", "List", "Product")
                    <span class="btn btn-info pull-right">
                        @Html.ActionLink(username + " - Logout", "logout", "Account")
                    </span>
                </h3>
                }
                else
                {
                    Html.ActionLink("login", "Account");
                }
            }
        
            @RenderBody()
        </div>
</body>
</html>